### ISSUE TITLE
[Wishlist] Add APEv2 cover reading (APE, WV, MPC, TAK)

### ISSUE THREAD

**Issue by Soukyuu** [bvbfan/Audio-thumbs#1]
Should be trivial since taglib supports the APE/WV formats. 

With TAK, taglib doesn't support it out of the box, but if you pass it as if it was a WV file, the tags and cover can be extracted just fine - more is not needed in this case.

**Comment by bvbfan** [comment]
Could you attach some sample files, i can't see how get cover art from APE/ID3v1.

**Comment by Soukyuu** [comment]
I think you need to iterate either through the propertyMap, or the itemListMap, and look for picture tags. 

Here's a sample file with a cover attached (10s "preview" style with all tags intact): [click](https://dl.dropboxusercontent.com/u/19330332/%E5%87%9B%E3%81%A8%E3%81%97%E3%81%A6%E6%99%82%E9%9B%A8%20-%20illusion%20is%20mine.wv)

**Comment by bvbfan** [comment]
I will update soon. Hope you can test and ogg files :)

**Comment by bvbfan** [comment]
Pull master and test. It has a problem with TAK, his mime type is application/octet-stream see https://www.filesuffix.com/en/extension/tak i made this plugin to be executed only for audio i.e. application/octet-stream is generic type it will affect many other files to be parsed from this plugin who can be potentially slow performed.

**Comment by Soukyuu** [comment]
Hmm, on my system (arch linux) wavpack files are registered as "audio/x-wavpack", not "audio/x-wv", and ape files are "audio/x-ape" not "audio/x-monkeys-audio", so pulling master didn't work. I haven't modified those values, so maybe the MIME type changed over time? You could check both, to be safe.

Ogg Vorbis works, as well as Ogg Opus.

Btw, another format using APEv2 tags is Musepack (MPC), MIME "audio/x-musepack".

And yeah, TAK is too obscure to have its own type. I don't know if it's possible, but you could work around that issue by providing a config dialog, where people could add entries, choosing the MIME-type and the tag type.

**Comment by bvbfan** [comment]
New version, please verify all (if you have file for test)

**Comment by Soukyuu** [comment]
Doesn't seem to work for any APE tags. 
I see you're picking the first binary tag, what if the file has more than one binary tag?
I think the `item.first` should be holding the name, maybe if you check for "PICTURE" or similar (I don't know which name it uses) it will be more robust.

Or does it work on your side with the sample file I gave you?

**Comment by bvbfan** [comment]
I saw unpack info
```
[toni@toni-pc ~]$ wvunpack -ss mine.wv 

 WVUNPACK  Hybrid Lossless Audio Decompressor  Linux Version 5.0.0
 Copyright (c) 1998 - 2016 David Bryant.  All Rights Reserved.


file name:         mine.wv
file size:         532061 bytes
source:            16-bit ints at 44100 Hz
channels:          2 (stereo)
duration:          0:00:10.00
modalities:        hybrid lossy, high, extra-4, dns
compression:       69.84%
ave bitrate:       426 kbps
encoder version:   5
original md5:      1752c7fb1f7676fd943a3e6899ea4469
source format:     Microsoft RIFF with 'wav' extension
file wrapper:      44 byte RIFF header

APEv2 tag items:   11
Track:             9/9
Album:             still a Shigure virgin?
Artist:            凛として時雨
Year:              2010
Genre:             Post-Hardcore/ Progressive Rock/ Indie Rock 
Title:             illusion is mine
replaygain_album_gain: -12.13 dB
replaygain_album_peak: 1.000000
replaygain_track_gain: -11.99 dB
replaygain_track_peak: 1.000000
Cover Art (Front): 27911-byte binary item (jpg)
```
Only one binay item, the last.

**Comment by bvbfan** [comment]
Does other types works?

**Comment by Soukyuu** [comment]
True, this file only has one, but wouldn't it be better to look for "Cover Art (Front)" instead?

In any case, it doesn't seem to work here with the sample file.

**Comment by bvbfan** [comment]
I saw the problem, first bytes are filename - most stupid thing i ever see

**Comment by bvbfan** [comment]
I rewrite all logic and your uploaded file should work as well as others, please verify.

**Comment by Soukyuu** [comment]
Yup, it's working now, thanks!
